env:
  - CXX=g++-4.8
  
language: node_js

node_js:
  - "stable"

before_script:
  - npm install -g gulp-cli mocha
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - export CHROME_BIN=chromium-browser

script:
  - npm run test-client
  - npm run test-server

services: mongodb

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8


